name: 'InterSystems Check Integrity'
description: 'Check integrity by identifying missing foreign keys'
inputs:
  namespace:
    description: 'Target namespace for the integrity check'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version: '1.24.1'
        cache: false

    - name: Check Integrity
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go run main.go \
          --namespace "${{ inputs.namespace }}" \

branding:
  icon: 'shield'
  color: 'green'
